<?xml version="1.0" encoding="UTF-8"?><testrun name="FelixTestConnexionImpossible" project="Felix_java" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testsuite name="vue.FelixTestConnexionImpossible" time="8.674">
    <testcase name="testConnexionSansCamix" classname="vue.FelixTestConnexionImpossible" time="8.674">
      <error>org.netbeans.jemmy.TimeoutExpiredException: Component having "Connexion Chat Felix" name.
	at org.netbeans.jemmy.Waiter.waitAction(Waiter.java:147)
	at org.netbeans.jemmy.WindowWaiter.waitWindow(WindowWaiter.java:412)
	at org.netbeans.jemmy.WindowWaiter.waitWindow(WindowWaiter.java:202)
	at org.netbeans.jemmy.FrameWaiter.waitFrame(FrameWaiter.java:221)
	at org.netbeans.jemmy.operators.FrameOperator.waitFrame(FrameOperator.java:411)
	at org.netbeans.jemmy.operators.JFrameOperator.&lt;init&gt;(JFrameOperator.java:72)
	at org.netbeans.jemmy.operators.JFrameOperator.&lt;init&gt;(JFrameOperator.java:85)
	at org.netbeans.jemmy.operators.JFrameOperator.&lt;init&gt;(JFrameOperator.java:93)
	at vue.FelixTestConnexionImpossible.recuperationVueConnexion(FelixTestConnexionImpossible.java:184)
	at vue.FelixTestConnexionImpossible.recuperationInterface(FelixTestConnexionImpossible.java:171)
	at vue.FelixTestConnexionImpossible.lanceInstance(FelixTestConnexionImpossible.java:154)
	at vue.FelixTestConnexionImpossible.setUp(FelixTestConnexionImpossible.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

</error>
    </testcase>
  </testsuite>
</testrun>
